# Generated by Django 4.1.2 on 2022-10-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutter_back', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
