# Generated by Django 4.1.2 on 2022-10-14 15:30

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutter_back', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='status_id',
        ),
        migrations.AddField(
            model_name='task',
            name='originalEstimate',
            field=models.CharField(max_length=1000, null=True, verbose_name='Исходная оценка времени'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(max_length=1000, null=True, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='task',
            name='startDate',
            field=models.CharField(max_length=1000, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя статуса'),
        ),
        migrations.AddField(
            model_name='task',
            name='timeSpent',
            field=models.CharField(max_length=1000, null=True, verbose_name='Затраченное время'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.CharField(max_length=1000, null=True, verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='jira_id',
            field=models.IntegerField(max_length=500, null=True, verbose_name='ID в Jira'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=1000, null=True, verbose_name='Название задачи'),
        ),
    ]
